### ISSUE TITLE
Client cannot connect to server

### ISSUE THREAD

**Issue by J4ckTh3R1pper** [kmcsr/login_proxy_mcdr#1]
I am using LoginProxy with SmartServerTime, but when my client tries to connect to server, an error occurs and the connection is failed.

System: Alpine Linux Running in Docker
Kernel: 5.10.0-21-amd64
Minecraft Server Version: 1.19 w/ fabric-0.14.8 (online-mode=false)
Python version: 3.11
MCDReforged Version: 2.9.0
Loginproxy Version 0.5.3

My LoginProxy config:
> {                 
    "minimum_permission_level": {
        "help": 0, 
        "list": 1,  
        "query": 2,
        "banned": 2,
        "ban": 2,   
        "banip": 3,   
        "pardon": 3,   
        "pardonip": 3,
        "whitelist": 2,
        "enable": 3,
        "disable": 3,
        "allow": 3, 
        "allowip": 3,
        "remove": 3,
        "removeip": 3
    },           
    "proxy_addr": {   
        "ip": "",    
        "port": 25565,    
        "ipv6": "::",
        "ipv6_port": 25566    
    },                           
    "enable_whitelist": false,
    "enable_ip_whitelist": false,      
    "whitelist_level": 3,
    "kick_cmd": "kick {name} {reason}",               
    "messages": {                              
        "banned.name": "Your account has been banned",           
        "banned.ip": "Your ip has been banned",          
        "whitelist.name": "Your account is not in the whitelist",
        "whitelist.ip": "Your ip is not in the whitelist"
    }

Traceback:
> [MCDR] [23:11:55] [lp_handler/WARNING]: Error when handle[[****]:*****]: EOF
Traceback (most recent call last):
  File "plugins/LoginProxy-v0.5.3.mcdr/loginproxy/server.py", line 382, in handle
    close_flag = not self.handle_login(conn, addr, login_data, pkt)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins/LoginProxy-v0.5.3.mcdr/loginproxy/server.py", line 413, in handle_login
    cls.login_parser_1_19(pkt, login_data)
  File "plugins/LoginProxy-v0.5.3.mcdr/loginproxy/server.py", line 465, in login_parser_1_19
    has_uuid = pkt.read_bool()
               ^^^^^^^^^^^^^^^
  File "plugins/LoginProxy-v0.5.3.mcdr/loginproxy/encoder.py", line 104, in read_bool
    v = self.read_byte()
        ^^^^^^^^^^^^^^^^
  File "plugins/LoginProxy-v0.5.3.mcdr/loginproxy/encoder.py", line 88, in read_byte
    v = self.read(1, err='EOF')
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins/LoginProxy-v0.5.3.mcdr/loginproxy/encoder.py", line 84, in read
    raise DecodeError(err)
loginproxy.encoder.DecodeError: EOF

**Comment by J4ckTh3R1pper** [comment]
problem persists in version 0.6.0, Traceback:
>[MCDR] [11:04:07] [lp_handler/WARNING]: Error when handle[[218.64.115.221]:53316]: 
Traceback (most recent call last):
  File "plugins/LoginProxy-v0.6.0.mcdr/loginproxy/server.py", line 530, in handle
    close_flag = not self.handle_ping_1_7(conn, addr, protocol, login_data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins/LoginProxy-v0.6.0.mcdr/loginproxy/server.py", line 649, in handle_ping_1_7
    if handle(self, conn, addr, login_data, res):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins/LoginProxy-v0.6.0.mcdr/loginproxy/server.py", line 356, in default_onping
    sokt = self.new_connection(login_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins/LoginProxy-v0.6.0.mcdr/loginproxy/server.py", line 372, in new_connection
    encode_short(login_data['port']) +
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins/LoginProxy-v0.6.0.mcdr/loginproxy/encoder.py", line 29, in encode_short
    assert 0 <= n and n <= 0xffff
                      ^^^^^^^^^^^
AssertionError

It would be hard for me to upgrade to 1.19.1+ because i've got too many mods to update along with the minecraft version

**Comment by zyxkad** [comment]
Hmm, that's different problem now

**Comment by J4ckTh3R1pper** [comment]
A different error occurs when running server locally
Traceback:
>[MCDR] [12:05:02] [lp_handler/INFO]: Player ************[[172.20.0.1]:60000] trying to join
[MCDR] [12:05:02] [lp_handler/WARNING]: Error when handle[[172.20.0.1]:60000]: 'has_uuid'
Traceback (most recent call last):
  File "plugins/LoginProxy-v0.6.0.mcdr/loginproxy/server.py", line 535, in handle
    close_flag = not self.handle_login(conn, addr, login_data, pkt)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins/LoginProxy-v0.6.0.mcdr/loginproxy/server.py", line 597, in handle_login
    if handle(self, conn, addr, name, login_data):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins/LoginProxy-v0.6.0.mcdr/loginproxy/server.py", line 337, in default_onlogin
    sokt = self.new_connection(login_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins/LoginProxy-v0.6.0.mcdr/loginproxy/server.py", line 390, in new_connection
    encode_bool(login_data['has_uuid']) +
                ~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'has_uuid'

the server is in offline mode

**Comment by zyxkad** [comment]
Try <https://github.com/kmcsr/login_proxy_mcdr/releases/tag/v0.6.1>
Have tested, no problem now

**Comment by zyxkad** [comment]
> problem persists in version 0.6.0, Traceback:
> 
> > [MCDR] [11:04:07] [lp_handler/WARNING]: Error when handle[[_**.**.__.__]:_****]:
> > Traceback (most recent call last):
> > File "plugins/LoginProxy-v0.6.0.mcdr/loginproxy/server.py", line 530, in handle
> > close_flag = not self.handle_ping_1_7(conn, addr, protocol, login_data)
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "plugins/LoginProxy-v0.6.0.mcdr/loginproxy/server.py", line 649, in handle_ping_1_7
> > if handle(self, conn, addr, login_data, res):
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "plugins/LoginProxy-v0.6.0.mcdr/loginproxy/server.py", line 356, in default_onping
> > sokt = self.new_connection(login_data)
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "plugins/LoginProxy-v0.6.0.mcdr/loginproxy/server.py", line 372, in new_connection
> > encode_short(login_data['port']) +
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "plugins/LoginProxy-v0.6.0.mcdr/loginproxy/encoder.py", line 29, in encode_short
> > assert 0 <= n and n <= 0xffff
> > ^^^^^^^^^^^
> > AssertionError
> 
> It would be hard for me to upgrade to 1.19.1+ because i've got too many mods to update along with the minecraft version

@J4ckTh3R1pper I cannot reproduce this problem, if you can reproduce it, open an new issue, thanks! :)
