### ISSUE TITLE
Plugin stuck in infinite UNLOAD when server stops

### ISSUE THREAD

**Issue by J4ckTh3R1pper** [kmcsr/login_proxy_mcdr#2]
System: Alpine Linux Running in Docker
Kernel: 5.10.0-21-amd64
Minecraft Server Version: 1.19 w/ fabric-0.14.8
Python version: 3.11
MCDReforged Version: 2.9.0
Loginproxy Version 0.5.3

My LoginProxy config:
> {                 
    "minimum_permission_level": {
        "help": 0, 
        "list": 1,  
        "query": 2,
        "banned": 2,
        "ban": 2,   
        "banip": 3,   
        "pardon": 3,   
        "pardonip": 3,
        "whitelist": 2,
        "enable": 3,
        "disable": 3,
        "allow": 3, 
        "allowip": 3,
        "remove": 3,
        "removeip": 3
    },           
    "proxy_addr": {   
        "ip": "",    
        "port": 25565,    
        "ipv6": "::",
        "ipv6_port": 25566    
    },                           
    "enable_whitelist": false,
    "enable_ip_whitelist": false,      
    "whitelist_level": 3,
    "kick_cmd": "kick {name} {reason}",               
    "messages": {                              
        "banned.name": "Your account has been banned",           
        "banned.ip": "Your ip has been banned",          
        "whitelist.name": "Your account is not in the whitelist",
        "whitelist.ip": "Your ip is not in the whitelist"
    }

Traceback:
> [MCDR] [23:49:55] [MainThread/INFO]: 等待服务端进程停止
[MCDR] [23:49:55] [MainThread/INFO]: 服务端进程返回代码: 0
[MCDR] [23:49:55] [MainThread/INFO]: 服务端已关闭
[MCDR] [23:49:55] [MainThread/INFO]: 正在关闭 MCDR
[MCDR] [23:49:55] [TaskExecutor/INFO] [delayexe]: Delay ExE is on UNLOAD
[MCDR] [23:49:55] [TaskExecutor/INFO] [smart_servertime]: Smart server time is on UNLOAD
[MCDR] [23:49:55] [TaskExecutor/INFO] [timed_quick_backup_multi]: 插件卸载，停止时钟
[MCDR] [23:49:55] [TaskExecutor/INFO] [loginproxy]: Login proxy is on UNLOAD
[MCDR] [23:50:05] [WatchDog/WARNING]: TaskExecutor 线程已经 10 秒没有响应了，可能出了些问题
[MCDR] [23:50:05] [WatchDog/WARNING]: 正在于 TaskExecutor 线程中运行的插件 (如果存在的话): loginproxy@0.5.3
[MCDR] [23:50:05] [WatchDog/WARNING]: 重建 TaskExecutor 中

**Comment by zyxkad** [comment]
Looks like sth caused deadlock

**Comment by zyxkad** [comment]
Try <https://github.com/kmcsr/login_proxy_mcdr/releases/tag/v0.6.0> if it fixed both of the issues.
I cannot install minecraft 1.19 to test right now because the school block it :(

**Comment by J4ckTh3R1pper** [comment]
Problem solved on v0.6.0
