### ISSUE TITLE
[BUG] Login failed due to negative port

### ISSUE THREAD

**Issue by Geniucker** [kmcsr/login_proxy_mcdr#3]
**Describe the bug**

**Relative versions**
- MCDReforged: latest 
- login_proxy: latest 
- Minecraft server: 1.19.2fabric  (online-mode=true)
- Minecraft client: fabric

**To Reproduce**
1. Set external reverse proxy with port larger than 32767(in my case 59032)
2. Login
3.

**Relative Plugins / Mods**

- example_plugin@1.2.3

**Expected behavior**
Login successfully

**Config**

<details>

```json

```

</details>

**Logs**

<details>

```

```

</details>

**Screenshots**

![Image_1696269671197.jpg](https://github.com/kmcsr/login_proxy_mcdr/assets/61449208/2765a2d1-d8f5-4d5a-86a9-cb49f6dd8a78)
![IMG_20231003_020153.jpg](https://github.com/kmcsr/login_proxy_mcdr/assets/61449208/d84c027b-369c-4cbf-a27c-2bf7ef84a47b)

**Additional context**
59032 and -6504 are the same in short type. Maybe some logics consider the port as short instead of unsigned short. 
Or the assert statement 0<=n<=0xffff may have some problem

**Comment by zyxkad** [comment]
Try <https://github.com/kmcsr/login_proxy_mcdr/releases/tag/v0.6.2>

**Comment by Geniucker** [comment]
> Try https://github.com/kmcsr/login_proxy_mcdr/releases/tag/v0.6.2

Sorry but it's not the latest commit. I've apply this commit [9766836](https://github.com/kmcsr/login_proxy_mcdr/commit/9766836d49b27dcca5f7372230fbdf3643484882) manually before open this issue. And the latest commit [c1315f7](https://github.com/kmcsr/login_proxy_mcdr/commit/c1315f7580eaa37c099093d69916ef7dc1c93b9f) works
